### ISSUE TITLE
How to be with mixins that adds nesting?

### ISSUE THREAD

**Issue by krutoo** [stylelint-scss/stylelint-config-standard-scss#184]
Hi, im trying to add `stylelint-config-standard-scss` to my project.

In my project i have `utils.scss` with mixins like:

```scss
@mixin my-mixin {
  display: block; // 1) some rules here
  border: 1px solid red;

  &::hover {
    border: 1px solid green;
  }
}
```

Previously I wrote style for my component like this:

```scss
@use '../utils.scss';

.my-component {
  @include utils.my-mixin; // 2) using mixin
  display: flex; // 3) override some rules from mixin
}
```

The new warning in Sass 1.77.7 tells me that i should move include after top level rules rules.

But I need to keep mixin on the top because of overriding rules.

---

After upgrade to Sass 1.77.7 i rewrote code like this:
```scss
@use '../utils.scss';

.my-component {
  @include utils.my-mixin; // 2) using mixin
};

.my-component {
  display: flex; // 3) override some rules from mixin
}
```

But now `stylelint-config-standard-scss` tells that I should has only one `.my-component` selector.

---

How can I properly rewrite code according to `stylelint-config-standard-scss` and new Sass nesting rules?
